import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@mantine/core/styles.css";
import "./globals.css";
import "./styles.css";
import { Navbar } from "@/components";
import {
  AppShell,
  Burger,
  Divider,
  Group,
  MantineProvider,
  createTheme,
} from "@mantine/core";
import { useDisclosure } from "@mantine/hooks";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = createTheme({
    fontFamily: "Montserrat, sans-serif",
    defaultRadius: "md",
  });

  const [opened, handlers] = useState();

  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <MantineProvider theme={theme}>
          <AppShell
            header={{ height: 60 }}
            navbar={{
              width: 300,
              breakpoint: "sm",
              collapsed: { mobile: !opened },
            }}
            padding="md"
          >
            <AppShell.Header>
              <Group h="100%" px="md">
                <Burger
                  opened={opened}
                  onClick={toggle}
                  hiddenFrom="sm"
                  size="sm"
                />
                <p>Dashboard Cut Made & Folded</p>
              </Group>
            </AppShell.Header>
            <AppShell.Navbar p="md">
              <Navbar style="flex flex-col w-1/4 border"></Navbar>
            </AppShell.Navbar>
            <AppShell.Main> {children}</AppShell.Main>
          </AppShell>
        </MantineProvider>
      </body>
    </html>
  );
}
